### ISSUE TITLE
Cannot access kubernetes from outside

### ISSUE THREAD

**Issue by andrebrito16** [garutilorenzo/k3s-oci-cluster#10]
Hello, I'm trying to access K8s API from outside, to use lens for example. I've tried to follow steps that [this](https://github.com/garutilorenzo/k3s-oci-cluster/issues/3) suggested but not working. Can you please help me?

**Comment by garutilorenzo** [comment]
Hi @andrebrito16, i've created a new branch kubeapi_public_access with this new feature. The code is **not** tested, but i think it will work.
If you want to test the code, you are welcome :)

**Comment by andrebrito16** [comment]
Thanks for help @garutilorenzo! I applied this and terraform apply runs without any errors. But I still getting timeout when trying to connect to kubernetes api via Lens, for example. :(

**Comment by garutilorenzo** [comment]
Fixed, a NSG rule was missing.

```
lorenzo@mint-virtual:~$ export KUBECONFIG=oci-kubeconfig.yaml
lorenzo@mint-virtual:~$ kubectl get nodes
NAME                     STATUS   ROLES                       AGE     VERSION
inst-cnhyq-k3s-servers   Ready    control-plane,etcd,master   6m8s    v1.24.3+k3s1
inst-gxrup-k3s-servers   Ready    control-plane,etcd,master   7m49s   v1.24.3+k3s1
inst-pmnj5-k3s-workers   Ready    <none>                      6m40s   v1.24.3+k3s1
inst-xjupx-k3s-workers   Ready    <none>                      6m45s   v1.24.3+k3s1
```
with this fix you have to destroy and recreate all the infrastructure.

**Comment by andrebrito16** [comment]
Thank you so much @garutilorenzo. Now it worked like a charm! And congrats for the excellent job!
