### ISSUE TITLE
Access service from outside using Nginx

### ISSUE THREAD

**Issue by andrebrito16** [garutilorenzo/k3s-oci-cluster#12]
Hello, I'm trying to access a service from URL, the ingress already exists but points to internal LB IP
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/30161990/185766004-5c818fd5-98a4-4d2a-b2c8-5e2e1e66cce1.png">

Can you please help me and tell how can I access my service from outside?

Ps: I have saw the nginx config for WP but I tried to use to my service but without success.

**Comment by garutilorenzo** [comment]
Hi @andrebrito16,

i can't understand your request.
Wath is the "URL" you are trying to access?
Have you configured the ingress rules? Can you paste your full deployment here?
Your application will be availalble at the defautl virtual host or you have to configure a domain? (Eg. example.com)

All your http(s) services will be available at <public_lb_ip> address, you have to configure:

* nginx (or your preferred web server)
* nginx ingress conntroller
* point your DNS record to public_lb_ip

To better understand how network in kubernetes work, read [this article])https://kubernetes.io/docs/concepts/services-networking/).

**Comment by andrebrito16** [comment]
Hi @garutilorenzo, sorry for this. I'm just starting with k8s concepts and devops. 

Here is my ingress.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/30161990/185904209-d24fe523-c6c0-4ebd-a6b3-8368af627624.png">

I've tested the same deploy on single-node k3s cluster, and it worked but at Load Balancers field on Lens I see the public IP of my VPS. Using terraform that you provided to run k3s at Oracle, I see only private IP address at Load Balancer on Lens. Idk how to point from outside to private IP LB. Thanks for attention :)
