### ISSUE TITLE
Alternative operating system support?

### ISSUE THREAD

**Issue by Djelibeybi** [garutilorenzo/k3s-oci-cluster#14]
First, thanks for creating such a useful Terraform module. It works great.

Are you interested in supporting a choice of operating system for the instances? I've created a downstream fork that allows you to chose either Ubuntu (which remains the default) or Oracle Linux as well as allows users to change the shape and resource allocation of the instances. 

I'm happy to submit the feature set as a PR if you want. If not, I'll probably remove the Ubuntu stuff and just maintain an Oracle Linux based fork downstream.

**Comment by garutilorenzo** [comment]
Hi @Djelibeybi yes sure, you can submit a new PR

**Comment by Djelibeybi** [comment]
I've done some refactoring and added the option of deploying the OCI Cloud Controller Manager during the install. I'll post the PR shortly so you can review and decide if it's still worth merging.

**Comment by garutilorenzo** [comment]
Hi @Djelibeybi I have created a new PR #20 for Oracle Linux OS support. I haven't used a variable for the OS determination but I check if */etc/lsb-release* exist. If true the OS is ubuntu, else is Oracle. The check can be improved.

I've tested both Oracle Linux 8 and 9

**Comment by Djelibeybi** [comment]
That's awesome. Will take it for a spin myself later today.

**Comment by garutilorenzo** [comment]
@Djelibeybi merged PR #20. I get most of the new features from your oraclelinux-oci-ccm branch and thank you for your revison on the PR.
In the next days I will open a new PR for the OCI CCM.

**Comment by Djelibeybi** [comment]
That's great. I didn't manage to take it for that spin last week, but will do so on Monday or Tuesday. 

You can go ahead and close this issue if you want, or keep it open for your own tracking purposes.

**Comment by Djelibeybi** [comment]
I didn't realise I'd left this issue open. My bad!
