### ISSUE TITLE
403 Forbidden access

### ISSUE THREAD

**Issue by davidpinhas** [garutilorenzo/k3s-oci-cluster#15]
Hi Lorenzo,

I've been following your steps and tested the mariadb/nginx/wordpress deployments, however, every time I attempt to access the wordpress service through the public LB IP, I'm getting HTTP error 403:
<img width="456" alt="image" src="https://user-images.githubusercontent.com/45331381/187006870-b1a644b4-4946-402b-84bd-290b09b42f59.png">

Steps to reproduce the issue:
1. `git clone https://github.com/garutilorenzo/k3s-oci-cluster.git`
2. add terraform.tfvars file under 'example' dir
3. run:
`$ tfinit && tfplan -out tfplan && tf apply -auto-approve "tfplan"`
4. exec to one of the server nodes
5. run "kubectl apply" command on all deployments:
```
$ sudo kubectl apply -f https://raw.githubusercontent.com/garutilorenzo/k3s-oci-cluster/master/deployments/mariadb/all-resources.yml
$ sudo kubectl apply -f https://raw.githubusercontent.com/garutilorenzo/k3s-oci-cluster/master/deployments/nginx/all-resources.yml
$ sudo kubectl apply -f https://raw.githubusercontent.com/garutilorenzo/k3s-oci-cluster/master/deployments/wordpress/all-resources.yml

$ sudo kubectl get pods
NAME                         READY   STATUS    RESTARTS   AGE
mariadb-fff96ccbd-9zvvd      1/1     Running   0          29m
nginx-86756dfb74-pzxbs       1/1     Running   0          29m
wordpress-7df665c44b-5tpng   1/1     Running   0          29m
```
6. accessing the public LB IP
```
$ curl http://$PUBLIC_LB_IP/wp-admin/install.php -v

*   Trying $PUBLIC_LB_IP:80...
* Connected to $PUBLIC_LB_IP ($PUBLIC_LB_IP) port 80 (#0)

> GET /wp-admin/install.php HTTP/1.1
> Host: $PUBLIC_LB_IP
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< Date: Sat, 27 Aug 2022 00:22:53 GMT
< Content-Type: text/html; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: PHP/7.4.30
< Expires: Wed, 11 Jan 1984 05:00:00 GMT
< Cache-Control: no-cache, must-revalidate, max-age=0
< X-Redirect-By: WordPress
< Location: http://$PUBLIC_LB_IP/wp-admin/install.php
<

* Connection #0 to host $PUBLIC_LB_IP left intact
```
Additional info:
variable "expose_kubeapi" in vars.tf file was set to True.
Manually added access for both 80/443 ports to my public ip CIDR in the Default security list.

Am I missing something?

I would like to also thank you for this great project and the amazing work you did with it!

**Comment by garutilorenzo** [comment]
Hi @davidpinhas this is a lack of documentation, I will update the readme asap.
To fix this problem download [nginx-deployment.yml](https://github.com/garutilorenzo/k3s-oci-cluster/blob/master/deployments/nginx/nginx-deployment.yml) or [all-resources.yml](https://github.com/garutilorenzo/k3s-oci-cluster/blob/master/deployments/nginx/all-resources.yml) and edit this line:

```yaml
- name: SECURE_SUBNET
  value: 8.8.8.8/32 # change-me
```

the SECURE_SUBNET env variable will be replaced in the  *wordpress-conf-tpl* -> [nginx-configmap.yml](https://github.com/garutilorenzo/k3s-oci-cluster/blob/master/deployments/nginx/nginx-configmap.yml).
This is for secure the WP installation and protect some specific url (wp-admin for example).

**Comment by davidpinhas** [comment]
Tested and confirmed it works, thanks!
