### ISSUE TITLE
Use Traefik 2 instead of nginx as ingress

### ISSUE THREAD

**Issue by mannp** [garutilorenzo/k3s-oci-cluster#19]
I wondered, if setting install_nginx_ingress = false, would still install Traefik 1 as the default ingress?

If so, is there a way to turn this off, so I can install Traefik 2?

Thanks.

Edit: Looking at the cluster, it looks like traefik 2.6 is installed, but not in its own namespace etc

Would there be any chance of having an option to say perhaps nginx ingress (Yes/No/None) the none being to apply --disable traefik without installing the nginx ingress.

```
%{ if install_nginx_ingress } 
disable_traefik="--disable traefik"
%{ endif }
```

That way, we can apply our own traefik 2 configs?

**Comment by garutilorenzo** [comment]
I can open a PR with *disable_disable_traefik* or *no_ingress_controller* so either nginx and traefik wouldn't be installed.
But I think you can remove treafik by removing the mainfest in **/var/lib/rancher/k3s/server/manifests**

[Ref](https://rancher.com/docs/k3s/latest/en/networking/#traefik-ingress-controller)

**Comment by mannp** [comment]
At some stage I was going to try and make a PR for adding traefik2, but not well atm, so wouldn't be for a while.

In potential; prep for that, I wondered if 'install_traefik_ingress = (Y/N)' would be more suitable?


**On a related but side note**

I also wondered if reading configs for ingress is possible/difficult with terraform, that way if a traefik_ingress.yml is there, it takes that as the config, rather than the default config here;
```

%{ if install_nginx_ingress }
if [[ "$first_last" == "first" ]]; then
  kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-${nginx_ingress_release}/deploy/static/provider/baremetal/deploy.yaml
  NGINX_RESOURCES_FILE=/root/nginx-ingress-resources.yaml
  render_nginx_config
  kubectl apply -f $NGINX_RESOURCES_FILE
fi
%{ endif }
```

**Comment by garutilorenzo** [comment]
I think that *install_traefik_ingress* will be reduntand since traefik is intalled by default by k3s.
Maybe a *install_traefik_v2* is more suitable, in this case:

- traefik v1 won't be installed
- traefik v2 will be installed

or maybe *disable_ingress*, in this case:

- traefik v1 won't be installed
- nginx ingress won't be installed

In this second scenario you are be able to install traefik v2 manually.

**Comment by mannp** [comment]
Either option work for me, I don't have any strong view either way.

Install_traefik_v2, would only really be of use if it were to be automatically installed, while disable_ingress, does the job of disabling traefik 1, to allow people to then do what they wish.

**Comment by mannp** [comment]
Hi @garutilorenzo wondered if you could help with my understanding of the oracle side of traefik2.

What I mean is, I have a stripped cluster without nginx ingress, traefik 1 ingress and servicelb; things are stable, and I am attempting to install traefik2.

My issue is that the public LB is showing a critical error, and I am unclear which external address to give to my traefik2 LB...

Should I be using the public LB address for traefik2?

I have this working elsewhere with metallb but I am unclear on the oracle elements if you are able to shed any light please?

Thank in advance

**Comment by garutilorenzo** [comment]
Hi @mannp,

yes as discussed in #23 this installation is a "bare metal" installation on OCI.
In other words, k3s doesn't know is installed on OCI and it has no ability to call OCI apis to get a public ip address. To do this k3s needs the OCI CCM (feature not available at the moment).
If Traefik2 is installed you have to correctly setup public load balancer, listener and backend set to redirect the traffic to the k3s worker (or server) with the right port where Traefik2 is listening.

**Comment by mannp** [comment]
> Hi @mannp,

Hi @garutilorenzo thanks for coming back to me. 

I only have a local k3s cluster working and cannot get my head around the Oracle changes needed.

> 
> yes as discussed in #23 this installation is a "bare metal" installation on OCI. In other words, k3s doesn't know is installed on OCI and it has no ability to call OCI apis to get a public ip address. To do this k3s needs the OCI CCM (feature not available at the moment). 

I understand the premise and envisage the only entry point into the cluster is the external Oracle LB address.

> If Traefik2 is installed you have to correctly setup public load balancer, listener and backend set to redirect the traffic to the k3s worker (or server) with the right port where Traefik2 is listening.

What I am not clear on, is; 

1) How is it that this all works with the default traefik 1 installed but appears to need so much extra work for traefik 2.

2) Do you mean the Oracle public load balancer, listener and backend set to redirect the traffic to the k3s worker (or server) where Traefik2 is listening?

**Comment by garutilorenzo** [comment]
Hi @mannp I've just created #27
Hope you will find all the answers here.

**Comment by mannp** [comment]
> Hi @mannp I've just created #27 Hope you will find all the answers here.

Cool, many thanks @garutilorenzo, I will close this now.

**Comment by mannp** [comment]
> 

Great, thanks 👍🏻
