### ISSUE TITLE
3 masters for ha 

### ISSUE THREAD

**Issue by lucacalcaterra** [garutilorenzo/k3s-oci-cluster#21]
@garutilorenzo first of all.. good work done ! Why not use 3 master for real ha ? Rancher suggest so and behind lb you can habe real ha . I'm wrong ? Ps saluti da un connazionale :-)

**Comment by garutilorenzo** [comment]
Ciao @lucacalcaterra :wave:

you are absolutly right. Three master nodes are needed for a "real ha".
With the Oracle free tier limitation I've splitted the resources 50% for the masters and 50% for the worksers.
With k3s all the masters are schedulable so, there is no problem having 3 masters and only one worker.

**Comment by garutilorenzo** [comment]
Ok, now I remember. I've already tried to deploy 3 masters but with the OCI always free account you can deploy max 2 instances for instance pool.
For a production use and with a "unlimited" account this is the best choice.

**Comment by lucacalcaterra** [comment]
> Ok, now I remember. I've already tried to deploy 3 masters but with the OCI always free account you can deploy max 2 instances for instance pool. For a production use and with a "unlimited" account this is the best choice.

Are you sure ? I can't find this limit on oracle site but probably i'm wrong...

**Comment by garutilorenzo** [comment]
Yep, I've tried with terraform.
But if you try to increse the instance number from the web console the result is the same

![ip-limit](https://user-images.githubusercontent.com/4757326/191767588-117885c7-8238-46b7-b2b8-2ca604edd86d.PNG)

**Comment by lucacalcaterra** [comment]
ah! probably because i'm still on free trial period :-( Thanks !
