### ISSUE TITLE
Add more node from other Oracle Cloud account

### ISSUE THREAD

**Issue by dlcvietnam** [garutilorenzo/k3s-oci-cluster#24]
Hello,
I have  2 OCI account using always free resource. Can i add node from account 2 to account 1 (setup this project) ?

**Comment by garutilorenzo** [comment]
Hello @dlcvietnam,

No since the two accounts can't communicate with private IPs.
You can reach different tenancy VCN with [VCN Peering](https://docs.oracle.com/en-us/iaas/Content/Network/Tasks/VCNpeering.htm). This module can't handle this config at the moment.
