### ISSUE TITLE
Trying to provision a new cluster but only getting timeouts recently

### ISSUE THREAD

**Issue by mannp** [garutilorenzo/k3s-oci-cluster#25]
Hi

I have successfully spun up clusters before, but as of now, I can only get timeouts.

It has been working after the latest commits (argocd) but I cannot get it working now.

I wondered if it is the same for others now, or works fine?

```
  install_nginx_ingress    = false
  install_certmanager      = false
  install_argocd           = false
```
Thanks.

```
module.k3s_cluster.oci_core_instance_pool.k3s_servers: Still creating... [59m30s elapsed]
module.k3s_cluster.oci_core_instance_pool.k3s_servers: Still creating... [59m40s elapsed]
module.k3s_cluster.oci_core_instance_pool.k3s_servers: Still creating... [59m50s elapsed]
module.k3s_cluster.oci_core_instance_pool.k3s_servers: Still creating... [1h0m0s elapsed]

```

```
╷
│ Error: Operation Timeout 
│ Provider version: 4.95.0, released on 2022-09-28.  
│ Service: Core Instance Pool 
│ Error Message: timeout while waiting for state to become 'STOPPED, RUNNING' (last state: 'PROVISIONING', timeout: 1h0m0s), you may need to increase the Terraform Operation timeouts for your resource to continue polling for longer 
│ Suggestion: Try increasing the timeout by referring to this document: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformtroubleshooting.htm#common_issues__timeoutwhilewaiting
│ 
│ 
│   with module.k3s_cluster.oci_core_instance_pool.k3s_servers,
│   on ../k3s-servers.tf line 1, in resource "oci_core_instance_pool" "k3s_servers":
│    1: resource "oci_core_instance_pool" "k3s_servers" {
│ 
╵

```
Not sure if it is of any consequence, but on destroying the failed cluster, I get;
```

│ Error: 409-Conflict, Invalid State Transition of NLB lifeCycle state from Updating to Updating
│ Suggestion: The resource is in a conflicted state. Please retry again or contact support for help with service: Network Load Balancer Listener
│ Documentation: https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/network_load_balancer_listener 
│ API Reference: https://docs.oracle.com/iaas/api/#/en/networkloadbalancer/20200501/Listener/DeleteListener 

```

**Comment by garutilorenzo** [comment]
Hi @mannp, 

all the commits on this repo was tested before merging, but I will try to provision a new cluster to check if the last commits are the problem.
I need some info: your region? have you other resurces deployed in the account you are using?
In some cases you can reach the timeout problem if you have reached a limit on the "free account".
Please check if you ave a  "orphan disk" in Storage -> Boot Volumes.
Please also check for error log in Compute -> Instance Pools -> k3s-servers -> Work request.

The error *409-Conflict* is a known issue. To solve this, repeat *terraform destroy*

**Comment by mannp** [comment]
> Hi @mannp,
> 
> all the commits on this repo was tested before merging, but I will try to provision a new cluster to check if the last commits are the problem. I need some info: your region? have you other resurces deployed in the account you are using? In some cases you can reach the timeout problem if you have reached a limit on the "free account". Please check if you ave a "orphan disk" in Storage -> Boot Volumes. Please also check for error log in Compute -> Instance Pools -> k3s-servers -> Work request.
> 


Hi @garutilorenzo I assumed they had been tested but did wonder if the last commit relating to the nginx LB might be doing something odd.

```
  availability_domain       = "NvwP:EU-FRANKFURT-1-AD-2"
  environment               = "prod"
  source                    = "../"
  install_nginx_ingress     = false
  install_certmanager       = false
  install_argocd            = false
  os_image_id               = "ocid1.image.oc1.eu-frankfurt 1.aaaaaaaaoulgsbl2wj2uth7prnsx2dpgdzx4gkergpo77yszyfwqhyyt2qgq" 
  k3s_load_balancer_name    = "K3s api LB" # It fails with or without this change
```

> Please check if you ave a "orphan disk" in Storage -> Boot Volumes.

I don't believe so. This is for every instance? I have tried 3 times today, so have a good few terminated instances.

> The error _409-Conflict_ is a known issue. To solve this, repeat _terraform destroy_

I see, and yes repeating is how I did it :)

**Comment by mannp** [comment]
> And when terraform is running, wath you see in: Compute -> Instance Pools -> k3s-servers -> Work request? You might see all the operations done by the instance pools and if there is an error, it will be listed here.

Apologies I looked and there was nothing in the log for the server, and I forgot to document above.

**Comment by mannp** [comment]
> I think you have some "dirty resources" on your account. So from the console clear all the resources, and run once again a terraform destroy. _Exceeded: vcn-count_ is very strange, so go to network and delete manually all the VCN.

I seem to have yes (namely some LBs) and have just manually deleted them, and I am trying again.

> So from the console clear all the resources, 

Not sure how to do that, is there a clear all type command?

**Comment by garutilorenzo** [comment]
No, you have to check all the resources one by one: Network, Storage, Compute (this are the main one). The module will create also one dynamic group so check under Identity & security

**Comment by mannp** [comment]
Dirty resources were indeed the issue.....sorry for the noise.
