### ISSUE TITLE
Change default server pool size to 1

### ISSUE THREAD

**Issue by sphr2k** [garutilorenzo/k3s-oci-cluster#26]
Nice procject :)

I would suggest changing the default size of the server pool to `1` as there is [no advantage to having an even number of etcd nodes](https://etcd.io/docs/v3.3/faq/#why-an-odd-number-of-cluster-members).

**Comment by mannp** [comment]
Interesting, 3 worker nodes would be handy.

Is it as simple as setting k3s_server_pool_size to 1, and k3s_worker_pool_size 3.

**Comment by sphr2k** [comment]
It should be as simple, yes. 

Of course, having only a single control plane node means no high availability, but so does having two, because one node being down equals loss of quorum. Usually, non-HA control plane is fine for hobby purposes.

**Comment by garutilorenzo** [comment]
Hi @sphr2k yes you are right 👍 
I will reduce the number of server from 2 to 1 and i will try to add an extra instance to the worker with *oci_core_instance_pool_instance* resource.
But @mannp is not possible to set *k3s_worker_pool_size* to 3 with a free account (no problem with paid account)
