### ISSUE TITLE
Default config issue: Longhorn install fails every time with the same issue.

### ISSUE THREAD

**Issue by mannp** [garutilorenzo/k3s-oci-cluster#28]
longhorn-driver-deployer fails to deploy every time, which in turn stops longhorn-manager and longhorn-admission-webhook

Search suggests it might be iscsi related, but nothing works as yet.

Have others had issues with the default longhorn deployment, if so any solution?

Thanks.

**Comment by mannp** [comment]
It is failing due to the version of k3s being installed is 'latest' while longhorn is only compatible with v1.24 k3s.

`Please ensure your Kubernetes cluster is at least v1.18 and at most v1.24 before upgrading to Longhorn v1.3.2 because the supported Kubernetes version has been updated (>= v1.18 and <= v1.24) in v1.3.2.`

FYI: Current latest releases;
```

variable "certmanager_release" {
  type    = string
  default = "v1.9.1"
}

variable "longhorn_release" {
  type    = string
  default = "v1.3.2"
}

variable "argocd_release" {
  type    = string
  default = "v2.4.15"
}
```

**Comment by garutilorenzo** [comment]
Hi @mannp as sayed in #29 in the documentation this *issue* has been described. I will close this issue.

**Comment by mannp** [comment]
Thanks @garutilorenzo :)

I'd understood the widely held view was not to use 'latest', especially when it relates to such an important item: the cluster version.

With the possibility in future there will be further incompatibilities.

Setting a compatible version of k3s across all options seemed sensible and if a user wants bleeding edge 'latest', they can surely choose it.
