### ISSUE TITLE
Incompatible provider version for `registry.terraform.io/hashicorp/template` package

### ISSUE THREAD

**Issue by erdkse** [garutilorenzo/k3s-oci-cluster#33]
Hey, thank you for your work. I really appreciate it. I am using MacOS M1 and I just can't install the package for terraform.

![Screenshot 2022-11-06 at 22 50 06](https://user-images.githubusercontent.com/2957624/200191821-0dacc363-fd85-4988-8b5f-e61ed32b2b44.png)

Do you plan to support it?

**Comment by garutilorenzo** [comment]
@erdkse  Can you please test with the latest commit?

**Comment by erdkse** [comment]
@garutilorenzo it is working mate! Grazie mille!
