### ISSUE TITLE
my_public_ip_cidr

### ISSUE THREAD

**Issue by csturiale** [garutilorenzo/k3s-oci-cluster#35]
Hi,
sorry for the question, how the value of the my_public_ip_cidr variable can be retrieved?
It's something related to https://docs.oracle.com/en-us/iaas/Content/General/Concepts/addressranges.htm ?
Thanks

**Comment by garutilorenzo** [comment]
Hi @csturiale,

this variable contains your public ip addr.
You can retrive it [here](https://www.whatsmyip.org/) for example.

**Comment by csturiale** [comment]
Hi @garutilorenzo , thanks a lot.
