### ISSUE TITLE
Error: did not find a proper configuration for private key

### ISSUE THREAD

**Issue by Giancarmine** [garutilorenzo/k3s-oci-cluster#43]
Hi @garutilorenzo,
First of all, thanks for the module!

I'm experimenting some problems when I try `terraform plan`

```
│ Error: can not create client, bad configuration: did not find a proper configuration for private key
│ 
│   with provider["registry.terraform.io/oracle/oci"],
│   on provider.tf line 10, in provider "oci":
│   10: provider "oci" {
│ 
```

Do you have any tip about?

**Comment by garutilorenzo** [comment]
mmmm I think you are in a bad directory. You have to execute terraform init, plan and apply in the `example` directory.
I'm seeing this "Enter a value: .." this happens if you are in the root directory of the repo.

**Comment by Giancarmine** [comment]
Mmmmm nope..

```bash
/home/el_giancar/views/k3s-oci-cluster/example
```

**Comment by garutilorenzo** [comment]
Can you paste the output of `terraform version`?

**Comment by Giancarmine** [comment]
Sure, I'm using tfenv to manage the terraform version 
```bash
➜  ~ terraform version
Terraform v1.3.9
on linux_amd64
```

**Comment by garutilorenzo** [comment]
Very strange, from your command output i can't see the provider version. If I run `terraform version` in the example dir this is the output:

```
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/oracle/oci v4.108.0
```

Did you run terraform init from the example dir?

**Comment by Giancarmine** [comment]
Yes, from example dir, now I'm downloading the `1.3.7 version` to test

**Comment by Giancarmine** [comment]
Ok, same error with this version

```
➜  example git:(master) ✗ terraform version
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/oracle/oci v4.108.0
```

**Comment by garutilorenzo** [comment]
I don't think using the main user is a problem. Maybe the private key is malformed or unreadable, but it's just a guess
Maybe setting terraform in [debugging](https://developer.hashicorp.com/terraform/internals/debugging) mode we can have more information.

**Comment by garutilorenzo** [comment]
@Giancarmine also make sure that /home/el_giancar/.oci/oci_api_key.pem is your private key, not public

**Comment by Giancarmine** [comment]
Yes, it is the private one but I'll re-generate a new key and I will re-try the full round to be sure about

**Comment by Giancarmine** [comment]
FIXED!!!

It was a malformation in the private key

Thank you so much to be patient and for the support!!!
