### ISSUE TITLE
Modifications needed to install Cilium

### ISSUE THREAD

**Issue by jorgnyg** [garutilorenzo/k3s-oci-cluster#45]
What kind of modifications are needed to successfully install Cilium on this setup?

Per [documentation](https://docs.cilium.io/en/stable/gettingstarted/k8s-install-default/) we need to set `INSTALL_K3S_EXEC='--flannel-backend=none --disable-network-policy'`.
But this seems to break the node connectivity, so I'm looking for some pointers on how communication should be configured/re-established.

**Comment by garutilorenzo** [comment]
Hi @jorgnyg, have you tried to ask @Cilium or @k3s support?
This repo is only a terraform module that automates the installation of k3s in OCI. The installation and configuration of Cilium is out of the scope of this repo.
