### ISSUE TITLE
2 AMD Workers

### ISSUE THREAD

**Issue by sjbr** [garutilorenzo/k3s-oci-cluster#6]
Can 2 AMD Worker Nodes be added to the cluster using the free AMD micro VMs?

Thanks

**Comment by garutilorenzo** [comment]
Hi @sjbr, 

No you can't run 2 AMD Worker nodes if you have 4 ARM instances. Please see the [docs](https://docs.oracle.com/en-us/iaas/Content/FreeTier/freetier_topic-Always_Free_Resources.htm).
And is not a good idea to mix architectures in a Kubernetes cluster.
